### ISSUE TITLE
production build failing due to UglifyJsPlugin removal

### ISSUE THREAD

**Issue by robintindale** [skpm/skpm#147]
When running `NODE_ENV='production' npm run build`, getting:

> `(node:53358) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.`

**Comment by mathieudutour** [comment]
fixed in https://github.com/skpm/skpm/commit/b2cd880a0e25006f10185f736b687fcdcafc4775

**Comment by romansp** [comment]
@robintindale, does it work for you now?

I still have an issue on my side. I get the following stack trace:

```
[1/2] 🖨  Copied src/manifest.json in 49ms
(node:2593) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot call a class as a function
(node:2593) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
